import Image from 'next/image';
import { site } from '../content/site';
import { Brand } from '../components/Brand';
import { ServiceIcon } from '../components/ServiceIcon';
import { Motion } from '../components/Motion';
const Arrow = () => <span aria-hidden="true">↗</span>;
function ConceptImage({ name, alt, hero = false }: { name: string; alt: string; hero?: boolean }) { return <figure className={hero ? 'hero-image' : 'detail-image'}><Image src={`/images/optimized/${name}.webp`} alt={alt} width={1536} height={1024} loading="eager" priority={hero} sizes={hero ? '(max-width: 800px) 100vw, 60vw' : '(max-width: 800px) 100vw, 50vw'} /><figcaption>{site.imageNote}</figcaption></figure>; }
export default function Home() { return <>
 <Motion />
 <a className="skip-link" href="#main">Skip to content</a>
 <header id="top" className="header"><div className="container header-inner"><Brand /><nav aria-label="Main navigation"><a href="#services">Services</a><a href="#details">The Details</a><a href="#contact">Contact</a></nav><a className="header-call" href={site.phoneHref}>Let’s talk <Arrow /></a></div></header>
 <main id="main">
 <section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span /> {site.location} · Carpentry & Home Services</p><h1 id="hero-title">Built Right.<br /> <em>Done Right.</em></h1><p className="hero-description">Siding, roofing, trim, window and door installation for your home.</p><a className="button" href={site.phoneHref}>Call for a Free Estimate <Arrow /></a><a className="text-link" href="#services">Explore Our Services <span aria-hidden="true">↓</span></a><p className="hero-bottom">Quality Craftsmanship You Can Trust</p></div><ConceptImage name="hero-coastal-house" alt="Conceptual coastal house with dark siding, white trim and a pitched roof; not a Vitor Carpentry project." hero /></section>
 <div className="service-strip" aria-hidden="true"><span>SIDING</span><i>✦</i><span>ROOFING</span><i>✦</i><span>TRIM</span><i>✦</i><span>WINDOWS</span><i>✦</i><span>DOORS</span></div>
 <section id="services" className="services section-pad"><div className="container"><div className="section-heading"><div><p className="eyebrow">01 / WHAT WE DO</p><h2>Every detail.<br />Every part of home.</h2></div><p>From your home’s exterior to its finishing touches, find the service for your next project.</p></div><div className="service-grid">{site.services.map((service, i) => <article className="service" key={service.name}><div className="service-top"><ServiceIcon kind={service.icon} /><span>0{i + 1}</span></div><h3>{service.name}</h3><p>{service.text}</p><p className="service-detail">{service.detail}</p></article>)}</div></div></section>
 <section id="details" className="details section-pad"><div className="container"><div className="section-heading"><div><p className="eyebrow">02 / THE FINISHING TOUCHES</p><h2>A home comes together<br />in the details.</h2></div><p>Siding. A clean window frame. A welcoming door. Explore the possibilities for your next project.</p></div><div className="detail-grid"><article><ConceptImage name="siding-window-detail" alt="Conceptual gray siding and white window trim detail; not a completed client project." /><div className="detail-label"><h3>A fresh look outside.</h3><span>Siding · Windows · Exterior trim</span></div></article><article><ConceptImage name="door-interior-trim" alt="Conceptual oak door with white interior casing and baseboard; not a completed client project." /><div className="detail-label"><h3>A thoughtful finish inside.</h3><span>Doors · Interior trim</span></div></article></div></div></section>
 <section id="contact" className="contact section-pad"><div className="container contact-inner"><div><p className="eyebrow">03 / LET’S GET STARTED</p><h2>Let’s Talk About<br />Your Next Project.</h2><p>Call or email to request a free estimate.</p><a className="button" href={site.phoneHref}>Call for a Free Estimate <Arrow /></a></div><div className="contact-links"><span className="contact-label">CALL VITOR CARPENTRY</span><a className="phone" href={site.phoneHref}>{site.phone} <Arrow /></a><span className="contact-label">PREFER EMAIL?</span><a className="email" href={site.emailHref}>{site.email} <Arrow /></a><p>{site.location}</p></div></div></section>
 </main><footer><div className="container footer-inner"><Brand /><p>Built Right. Done Right.</p><a href="#top">Back to top ↑</a></div><div className="container preview-note">Design preview · Content and contact details pending confirmation. Concept images are illustrative and do not represent Vitor Carpentry projects.</div></footer>
 <a className="mobile-call" href={site.phoneHref}>Call for a Free Estimate <Arrow /></a>
 </>; }

